### ISSUE TITLE
Maze3D

### ISSUE THREAD

**Issue by NimrodDickler** [College-Maze/Maze#1]
toSting - Why did you use StringBuilder?

GetPossibleMoves - Why are you returning up,down, left ... and not the possitions ({x,y,z}).
GetPossibleMoves - why do you have the test !clonedPosition.equals(p) - you were just there and moved, it's not possible that you are still there (there = p).
m_currentPosition - why do you have the current position inside the maze? 
GetCrossSectionByX\Y\Z - I need you to explain what you did there.

**Comment by Elroie** [comment]
* the StringBuilder just make it easier to move to the next line. (we dont have to but it still look better)
another thing is that efficiency, StringBuilder is more efficient than regular String in some cases.

* GetPossibleMoves should return String[] by design (this is what they want...)

* you are right about the equals check (i had a bug and i tried to figure out its source)

*we should keep the current position inside the maze because this will later represent our player position inside the maze

* the GetCrossPosition is just a slice from a 3D array so i manipulated this to return slices by the index they asked for. (but we can still sit on it if you want)
