### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by NimrodDickler** [College-Maze/Maze#2]
Move(String move) - what is it doing and why do you have it.
equals(Object obj) - I need you to explain what is the first part (the part with obj)

**Comment by Elroie** [comment]
this is auto generated implementation of the equals method (it cover all the spot you need before you are trying to check equality between this specific object)

check if those instances are the same...
		if (this == obj) {
			return true;
		}

check if the object is null (we have to check this)
		if (obj == null) {
			return false;
		}

check that we are trying to equals two instances from the same class
		if (getClass() != obj.getClass()) {
			return false;
		}

otherwise we will try to do something illegal and we will fall during runtime
